name: jobs
on:
  workflow_dispatch

jobs:
  job_1:
    runs-on: ubuntu-latest

    steps:
      - run: |
          npm install
          npm run build 
          working-dircetory: ./temp
          shell: bash

    
    
